# Generated by Django 6.1 on 2026-08-14 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_maintenancerecord_mechanic_paybill_and_more'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_phone', models.CharField(max_length=20, verbose_name="Payer's Phone")),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Mechanic/Garage')),
                ('recipient_phone', models.CharField(blank=True, max_length=20, verbose_name='Mechanic Phone/Paybill')),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True, verbose_name='M-Pesa Receipt No.')),
                ('result_code', models.CharField(blank=True, max_length=10, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — PIN not entered yet'), ('COMPLETED', 'Payment Successful'), ('FAILED', 'Payment Failed / Cancelled')], default='PENDING', max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('maintenance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='maintenance.maintenancerecord')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.DeleteModel(
            name='MpesaTransaction',
        ),
    ]
