# Generated by Django 6.1 on 2026-08-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('mileage_at_service', models.PositiveIntegerField()),
                ('service_type', models.CharField(choices=[('ROUTINE', 'Routine Service'), ('REPAIR', 'Repair'), ('REPLACEMENT', 'Part Replacement'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('parts_replaced', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='cars.car')),
            ],
            options={
                'ordering': ['-service_date'],
            },
        ),
    ]
