# Generated by Django 6.1 on 2026-08-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='service_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
