# Generated by Django 6.1 on 2026-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenancerecord_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='service_type',
            field=models.CharField(choices=[('ROUTINE', 'Routine Service'), ('REPAIR', 'Repair'), ('REPLACEMENT', 'Part Replacement'), ('OIL CHANGE', 'oil change'), ('TYRES / ALIGNMENT', 'tyres / alignment'), ('INSURANCE', 'insurance'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
