# Generated by Django 6.1 on 2026-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_alter_maintenancerecord_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='mechanic_paybill',
            field=models.CharField(blank=True, help_text='Enter Paybill/Till number if paying directly to their business', max_length=50, null=True, verbose_name='Paybill Number'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='mechanic_phone',
            field=models.CharField(blank=True, help_text='Phone number of the person or garage to receive payment', max_length=20, null=True, verbose_name='Mechanic/Garage Phone Number'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='service_type',
            field=models.CharField(choices=[('ROUTINE', 'Routine Service'), ('REPAIR', 'Repair'), ('REPLACEMENT', 'Part Replacement'), ('OIL_CHANGE', 'Oil Change'), ('TYRES / ALIGNMENT', 'Tyres / Alignment'), ('INSURANCE', 'Insurance'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
